/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { RaceChainBetting__factory } from "./RaceChainBetting__factory";
export { TestRaceCoin__factory } from "./TestRaceCoin__factory";
