/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { RaceChainBetting } from "./RaceChainBetting";
export type { TestRaceCoin } from "./TestRaceCoin";
