/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface RaceChainBettingInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "bets"
      | "clearSelectionOutcome"
      | "owner"
      | "placeBet"
      | "renounceOwnership"
      | "selectionOutcomes"
      | "setSelectionOutcome"
      | "settleBet"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "BetPlaced"
      | "BetSettled"
      | "OwnershipTransferred"
      | "SelectionOutcomeUpdated"
  ): EventFragment;

  encodeFunctionData(functionFragment: "bets", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "clearSelectionOutcome",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "placeBet",
    values: [BigNumberish, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "selectionOutcomes",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setSelectionOutcome",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "settleBet",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "bets", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "clearSelectionOutcome",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "placeBet", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "selectionOutcomes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setSelectionOutcome",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "settleBet", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace BetPlacedEvent {
  export type InputTuple = [
    user: AddressLike,
    betId: BigNumberish,
    stake: BigNumberish,
    odds: BigNumberish,
    selectionId: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    betId: bigint,
    stake: bigint,
    odds: bigint,
    selectionId: bigint
  ];
  export interface OutputObject {
    user: string;
    betId: bigint;
    stake: bigint;
    odds: bigint;
    selectionId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BetSettledEvent {
  export type InputTuple = [
    betId: BigNumberish,
    user: AddressLike,
    result: string
  ];
  export type OutputTuple = [betId: bigint, user: string, result: string];
  export interface OutputObject {
    betId: bigint;
    user: string;
    result: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SelectionOutcomeUpdatedEvent {
  export type InputTuple = [
    selectionId: BigNumberish,
    position: BigNumberish,
    impliedOdds: BigNumberish
  ];
  export type OutputTuple = [
    selectionId: bigint,
    position: bigint,
    impliedOdds: bigint
  ];
  export interface OutputObject {
    selectionId: bigint;
    position: bigint;
    impliedOdds: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface RaceChainBetting extends BaseContract {
  connect(runner?: ContractRunner | null): RaceChainBetting;
  waitForDeployment(): Promise<this>;

  interface: RaceChainBettingInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  bets: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, bigint, string] & {
        stake: bigint;
        odds: bigint;
        selectionId: bigint;
        user: string;
      }
    ],
    "view"
  >;

  clearSelectionOutcome: TypedContractMethod<
    [selectionId: BigNumberish],
    [void],
    "nonpayable"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  placeBet: TypedContractMethod<
    [
      betId: BigNumberish,
      stake: BigNumberish,
      odds: BigNumberish,
      selectionId: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  selectionOutcomes: TypedContractMethod<
    [arg0: BigNumberish],
    [[bigint, bigint] & { position: bigint; impliedOdds: bigint }],
    "view"
  >;

  setSelectionOutcome: TypedContractMethod<
    [
      selectionId: BigNumberish,
      position: BigNumberish,
      impliedOdds: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  settleBet: TypedContractMethod<
    [betId: BigNumberish],
    [boolean],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "bets"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, bigint, string] & {
        stake: bigint;
        odds: bigint;
        selectionId: bigint;
        user: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "clearSelectionOutcome"
  ): TypedContractMethod<[selectionId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "placeBet"
  ): TypedContractMethod<
    [
      betId: BigNumberish,
      stake: BigNumberish,
      odds: BigNumberish,
      selectionId: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "selectionOutcomes"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [[bigint, bigint] & { position: bigint; impliedOdds: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "setSelectionOutcome"
  ): TypedContractMethod<
    [
      selectionId: BigNumberish,
      position: BigNumberish,
      impliedOdds: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "settleBet"
  ): TypedContractMethod<[betId: BigNumberish], [boolean], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "BetPlaced"
  ): TypedContractEvent<
    BetPlacedEvent.InputTuple,
    BetPlacedEvent.OutputTuple,
    BetPlacedEvent.OutputObject
  >;
  getEvent(
    key: "BetSettled"
  ): TypedContractEvent<
    BetSettledEvent.InputTuple,
    BetSettledEvent.OutputTuple,
    BetSettledEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "SelectionOutcomeUpdated"
  ): TypedContractEvent<
    SelectionOutcomeUpdatedEvent.InputTuple,
    SelectionOutcomeUpdatedEvent.OutputTuple,
    SelectionOutcomeUpdatedEvent.OutputObject
  >;

  filters: {
    "BetPlaced(address,uint32,uint256,uint16,uint32)": TypedContractEvent<
      BetPlacedEvent.InputTuple,
      BetPlacedEvent.OutputTuple,
      BetPlacedEvent.OutputObject
    >;
    BetPlaced: TypedContractEvent<
      BetPlacedEvent.InputTuple,
      BetPlacedEvent.OutputTuple,
      BetPlacedEvent.OutputObject
    >;

    "BetSettled(uint32,address,string)": TypedContractEvent<
      BetSettledEvent.InputTuple,
      BetSettledEvent.OutputTuple,
      BetSettledEvent.OutputObject
    >;
    BetSettled: TypedContractEvent<
      BetSettledEvent.InputTuple,
      BetSettledEvent.OutputTuple,
      BetSettledEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "SelectionOutcomeUpdated(uint32,uint8,uint16)": TypedContractEvent<
      SelectionOutcomeUpdatedEvent.InputTuple,
      SelectionOutcomeUpdatedEvent.OutputTuple,
      SelectionOutcomeUpdatedEvent.OutputObject
    >;
    SelectionOutcomeUpdated: TypedContractEvent<
      SelectionOutcomeUpdatedEvent.InputTuple,
      SelectionOutcomeUpdatedEvent.OutputTuple,
      SelectionOutcomeUpdatedEvent.OutputObject
    >;
  };
}
